### ISSUE TITLE
Is this the official repo for the npmjs module 'open' ?

### ISSUE THREAD

**Issue by jsoverson** [pwnall/node-open#10]
The [package.json](https://github.com/pwnall/node-open/blob/master/package.json#L14) and subsequently [npmjs.org](https://npmjs.org/package/open)  references the fork https://github.com/jjrdn/node-open which doesn't actually seem active.

**Comment by pwnall** [comment]
Thank you for catching this, @jsoverson! I fixed it on master, and the next release will have the correct pointers.
