### ISSUE TITLE
Does not work with Ubuntu 13.04

### ISSUE THREAD

**Issue by FoxGit** [pwnall/node-open#12]
https://github.com/onehealth/grunt-open/issues/5

Hi, I cannot use the grunt-plugin which uses this plugin with Ubuntu as the `xdg-open` command is not referenced correctly. For more details please see my previous thread linked above.

Thank you

**Comment by FoxGit** [comment]
It works now. I think the xgd-open command is now integrated in this project unlike before. But to be honest I don't know for sure which change fixed the problem. Thanks, nonetheless :D

**Comment by Mithgol** [comment]
I can't see any [commits](https://github.com/pwnall/node-open/commits/master) in the last two days, so there's no change unless you have been using an old version and upgraded.
