### ISSUE TITLE
Does not open from Windows Service

### ISSUE THREAD

**Issue by ondreian** [pwnall/node-open#17]
I have a node.js app that watches a folder and opens files dropped in it in their relevant programs, when I turned it into a windows service open(file, 'program') stopped working.

**Comment by Mithgol** [comment]
It probably works, but uses the service's user (usually `SYSTEM`) and you don't see that user's windows on your desktop. (You should still be able to see that the `'program'` running if you open the Task Manager though.)

**Comment by ondreian** [comment]
I had changed the service user to the current user of windows that is running the node.js app, so I didn't think that should have been the issue.  On the off chance I made a mistake I went back and just verified that I had changed the service user, and I had.

**Comment by Mithgol** [comment]
If you open the Task Manager, is it possible see that the `'program'` starts after `open(file, 'program')`?
