### ISSUE TITLE
jshint yields 'redefinition of open'

### ISSUE THREAD

**Issue by niftylettuce** [pwnall/node-open#3]
when using syntax checking via syntastic for example

**Comment by jjrdn** [comment]
Can you give me more information on this?

I'm using jshint 0.9.1 and cannot reproduce this.  I assume we are talking about lib/open.js?

**Comment by pwnall** [comment]
Closing due to lack of response from @niftylettuce.

**Comment by backflip** [comment]
I'm having the same issue. Using `var open = require('open');` in my `gulpfile.js` throws above error message when hinting the file using https://sublime.wbond.net/packages/JSHint%20Gutter in Sublime Text 3.

**Comment by feross** [comment]
`window.open` exists in the browser. If you have `{ browser: true }` in your `.jshintrc` it must think that you're overwriting it.

**Comment by niftylettuce** [comment]
thanks @feross, just encountered this again and it makes sense
