### ISSUE TITLE
Opening PDF file on Heroku site?

### ISSUE THREAD

**Issue by kevinmachstudio** [pwnall/node-open#51]
When I'm running my Node.js application locally in my development environment, the PDF opens fine in a new tab, but when I'm on the live Heroku site, the PDF does not open at all.  Any ideas on why this is happening and how to solve this issue?

**Comment by pwnall** [comment]
This is meant for local tools, such as testing scripts. In a Web app, you probably want to redirect the user to a URL that you use to serve the PDF.

**Comment by kevinmachstudio** [comment]
I'm opening the url of the PDF that's hosted on AWS using "open(url);". The url is definitely there, but no opening occurs. Shouldn't the code be the same locally and in production?

**Comment by kevinmachstudio** [comment]
I see. Thanks Victor!
