### ISSUE TITLE
Support for multiple browsers

### ISSUE THREAD

**Issue by leostera** [pwnall/node-open#6]
It would be great to specify which browser to use and in case it's not installed, fallback to the default.

``` js
open(url,browserName);
```

**Comment by pwnall** [comment]
This should work as of node-open 0.0.3. Is there a specific case that doesn't work for you?

**Comment by Mithgol** [comment]
Someone should really update `README.md` to make this new feature documented. And with an example.

(I'd pull a request if I weren't busy IRL.)

**Comment by pwnall** [comment]
@Mithgol I finally got around to updating the README. Thank you for bringing this up, and please let me know if you find more issues!

**Comment by Mithgol** [comment]
No more issues, 195f61da9bc25fb3f066ca08c1b4fa9351c014d9 is fine.
